name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/pnpm

  prettier:
    name: Run Prettier
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Prettier check
        run: pnpm format.check

  eslint:
    name: Run ESLint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: ESLint check
        run: pnpm lint

  vitest:
    name: Run Vitest
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Vitest tests
        run: pnpm test
